# Generated by Django 4.2 on 2023-04-04 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instrumentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=512, verbose_name="Número")),
                (
                    "arquivo",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Laboratorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=512)),
            ],
            options={
                "verbose_name": "Laboratório",
            },
        ),
        migrations.CreateModel(
            name="OrdemDeServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "arquivo",
                    models.FileField(
                        blank=True, null=True, upload_to="ordens_de_servico/"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, max_digits=2, max_length=8),
                ),
                ("data", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ordem de serviço",
                "verbose_name_plural": "Ordens de serviço",
            },
        ),
        migrations.CreateModel(
            name="Referencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=512)),
            ],
            options={
                "verbose_name": "Referência",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Status",
            },
        ),
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("erro", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="calibracoes.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Criterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=512)),
                (
                    "referencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calibracoes.referencia",
                        verbose_name="Referência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Critério",
            },
        ),
        migrations.CreateModel(
            name="Calibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validade", models.IntegerField(help_text="Validade em dias")),
                (
                    "certificado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="calibracoes.certificado",
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="calibracoes.criterio",
                        verbose_name="Critério",
                    ),
                ),
                (
                    "instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instrumentos.instrumento",
                    ),
                ),
                (
                    "laboratorio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="calibracoes.laboratorio",
                        verbose_name="Laboratório",
                    ),
                ),
                (
                    "ordem_de_servico",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="calibracoes.ordemdeservico",
                        verbose_name="Ordem de serviço",
                    ),
                ),
                (
                    "resultado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="calibracoes.resultado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calibração",
                "verbose_name_plural": "Calibrações",
            },
        ),
    ]
