# Generated by Django 4.2 on 2023-05-15 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0002_instrumento_ordem_de_compra'),
        ('calibracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibracao',
            options={'ordering': ('data',), 'verbose_name': 'Calibração', 'verbose_name_plural': 'Calibrações'},
        ),
        migrations.AddField(
            model_name='calibracao',
            name='data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calibracao',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibracoes', to='instrumentos.instrumento'),
        ),
        migrations.AlterField(
            model_name='calibracao',
            name='ordem_de_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibracoes.ordemdeservico', verbose_name='Ordem de serviço'),
        ),
    ]
