# Generated by Django 4.2 on 2023-05-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracoes', '0002_alter_calibracao_options_calibracao_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibracao',
            name='validade',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='data',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='calibracao',
            name='data_proxima_calibracao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='calibracao',
            name='data_proxima_checagem',
            field=models.DateField(null=True),
        ),
    ]
