# Generated by Django 4.2 on 2023-05-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracoes', '0003_remove_calibracao_validade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibracao',
            options={'ordering': ('id',), 'verbose_name': 'Calibração', 'verbose_name_plural': 'Calibrações'},
        ),
        migrations.AlterField(
            model_name='calibracao',
            name='data',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calibracao',
            name='data_proxima_calibracao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calibracao',
            name='data_proxima_checagem',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
