# Generated by Django 4.2 on 2023-05-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracoes', '0004_alter_calibracao_options_alter_calibracao_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibracao',
            name='data',
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
