# Generated by Django 4.2 on 2023-05-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracoes', '0005_remove_calibracao_data_alter_ordemdeservico_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibracao',
            name='data',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
