# Generated by Django 4.2 on 2023-05-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0002_alter_cliente_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="inscricao_estadual",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Inscrição Estadual"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="isento",
            field=models.BooleanField(default=False),
        ),
    ]
