# Generated by Django 4.2 on 2023-04-04 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bairro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=212)),
            ],
        ),
        migrations.CreateModel(
            name="UF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sigla", models.CharField(max_length=2)),
            ],
            options={
                "verbose_name": "UF",
                "verbose_name_plural": "UFs",
            },
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.CharField(max_length=10, verbose_name="CEP")),
                ("numero", models.IntegerField(verbose_name="Número")),
                ("logradouro", models.TextField()),
                ("complemento", models.TextField(blank=True, null=True)),
                (
                    "bairro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enderecos.bairro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endereço",
            },
        ),
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=212)),
                (
                    "uf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cidades",
                        to="enderecos.uf",
                        verbose_name="UF",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bairro",
            name="cidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bairros",
                to="enderecos.cidade",
            ),
        ),
    ]
