# Generated by Django 4.2 on 2023-04-04 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fabricante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="Localizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=512)),
            ],
            options={
                "verbose_name": "Localização",
                "verbose_name_plural": "Localizações",
            },
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=512)),
                (
                    "fabricante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelos",
                        to="instrumentos.fabricante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdemDeCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=512)),
                (
                    "arquivo",
                    models.FileField(
                        blank=True, null=True, upload_to="ordens_de_compra/"
                    ),
                ),
                ("data", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Ordens de compra",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=512)),
            ],
            options={
                "verbose_name_plural": "Status",
            },
        ),
        migrations.CreateModel(
            name="TipoDeInstrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_de_serie",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Número de série",
                    ),
                ),
                (
                    "resolucao",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Resolução"
                    ),
                ),
                ("unidade", models.CharField(max_length=512)),
                ("faixa_nominal", models.CharField(max_length=512)),
                (
                    "modelo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="instrumentos.modelo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tipos de instrumento",
            },
        ),
        migrations.CreateModel(
            name="Instrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=512)),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrumentos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "localizacao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="instrumentos.localizacao",
                        verbose_name="Localização",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="instrumentos.status",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="instrumentos.tipodeinstrumento",
                    ),
                ),
            ],
        ),
    ]
