# Generated by Django 4.2 on 2023-05-15 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='ordem_de_compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instrumentos.ordemdecompra'),
        ),
    ]
