# Generated by Django 4.2 on 2023-05-17 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0003_alter_ordemdecompra_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumento",
            name="ordem_de_compra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="instrumentos.ordemdecompra",
            ),
        ),
    ]
